In [1]:
import pandas as pd
df = pd.read_csv("train.csv")
df.head()

,label,user_id,X1,X2,X3,X4,X5,X6,X7,X8,...,X42,X43,X44,X45,X46,X47,X48,X49,X50,X51
0,0,1,20972,14,13,3,11,1,2,15,...,0,0,0,0,0,0,0,0,1,0
1,0,2,7362,213,71,3,11,1,2,15,...,0,0,0,0,0,0,0,0,0,0
2,0,3,21216,215,71,3,11,1,2,15,...,0,0,0,0,0,0,0,0,0,0
3,0,4,2261,212,71,2,8,1,2,15,...,0,0,0,0,0,0,0,1,0,0
4,0,5,4543,213,71,2,8,1,2,15,...,0,0,0,0,0,0,0,0,0,0

In [2]:
import numpy as np
print("Input data shape:", np.array(df).shape)
print()
print(df.columns)

Input data shape: (458798, 53)

Index(['label', 'user_id', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8',
       'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18',
       'X19', 'X20', 'X21', 'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28',
       'X29', 'X30', 'X31', 'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X38',
       'X39', 'X40', 'X41', 'X42', 'X43', 'X44', 'X45', 'X46', 'X47', 'X48',
       'X49', 'X50', 'X51'],
      dtype='object')

In [3]:
df = df.drop(columns=["user_id"])
X = df[df.columns[1:]]
y = df["label"]

X = np.array(X)
y = np.array([y]).T
print(X.shape, y.shape)

(458798, 51) (458798, 1)

In [4]:
val_size = int(X.shape[0]*0.05)

xtrain = X[val_size:]
xval = X[:val_size]

ytrain = y[val_size:]
yval = y[:val_size]

#xtrain = xtrain.reshape((-1,1))
#xval = xval.reshape((-1,1))
#ytrain = ytrain.reshape((-1,1))
#yval = yval.reshape((-1,1))

print(f"xtrain shape =\t\t{xtrain.shape}\nxvalidation shape =\t{xval.shape}")
print()
print(f"ytrain shape =\t\t{ytrain.shape}\nyvalidation shape =\t{yval.shape}")

xtrain shape =		(435859, 51)
xvalidation shape =	(22939, 51)

ytrain shape =		(435859, 1)
yvalidation shape =	(22939, 1)

In [8]:
import tensorflow as tf
import keras as k
import keras.layers as l

np.random.seed(0)
model = k.Sequential([
    l.Input(shape=(51,)),
    l.Dense(126, activation="relu"),
    l.Dense(51, activation="softmax"),
    l.Flatten()
])
model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"])
h = model.fit(x=xtrain, y=ytrain, epochs=10, validation_data=(xval, yval,), batch_size=1000)
model.summary()

Epoch 1/10
436/436 [==============================] - 1s 2ms/step - loss: 0.3859 - accuracy: 0.0041 - val_loss: 0.0259 - val_accuracy: 0.0000e+00
Epoch 2/10
436/436 [==============================] - 1s 2ms/step - loss: 0.1304 - accuracy: 0.0132 - val_loss: 0.0259 - val_accuracy: 0.0000e+00
Epoch 3/10
436/436 [==============================] - 1s 2ms/step - loss: 0.1309 - accuracy: 0.0023 - val_loss: 0.0259 - val_accuracy: 0.0000e+00
Epoch 4/10
436/436 [==============================] - 1s 2ms/step - loss: 0.1308 - accuracy: 0.0011 - val_loss: 0.0259 - val_accuracy: 0.0000e+00
Epoch 5/10
436/436 [==============================] - 1s 2ms/step - loss: 0.1303 - accuracy: 0.0020 - val_loss: 0.0259 - val_accuracy: 0.0000e+00
Epoch 6/10
436/436 [==============================] - 1s 2ms/step - loss: 0.1302 - accuracy: 0.0045 - val_loss: 0.0259 - val_accuracy: 0.0000e+00
Epoch 7/10
436/436 [==============================] - 1s 2ms/step - loss: 0.1309 - accuracy: 0.0059 - val_loss: 0.0259 - val_accuracy: 0.0000e+00
Epoch 8/10
436/436 [==============================] - 1s 2ms/step - loss: 0.1301 - accuracy: 0.0215 - val_loss: 0.0259 - val_accuracy: 0.0000e+00
Epoch 9/10
436/436 [==============================] - 1s 2ms/step - loss: 0.1309 - accuracy: 0.0160 - val_loss: 0.0259 - val_accuracy: 0.0000e+00
Epoch 10/10
436/436 [==============================] - 1s 2ms/step - loss: 0.1305 - accuracy: 0.0077 - val_loss: 0.0259 - val_accuracy: 0.0000e+00
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_7 (Dense)              (None, 126)               6552
_________________________________________________________________
dense_8 (Dense)              (None, 51)                6477
_________________________________________________________________
flatten_3 (Flatten)          (None, 51)                0
=================================================================
Total params: 13,029
Trainable params: 13,029
Non-trainable params: 0
_________________________________________________________________